// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "C:/Users/jang9/OneDrive/Desktop/Coding/Genshin_Artifact_Simulator/Simulator.C";

#endif
